---
name: 🐛 Bug Report
description: Report a bug or problem with the PairTranslate extension
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report! A short, clear repro is the fastest way to get this fixed.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area is affected?
      options:
        - Website compatibility
        - Translation service / API / LLM
        - Translation triggering / selection
        - UI / settings
        - Performance
        - Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL (if applicable)
      description: The exact URL where it happens.
      placeholder: https://example.com/path

  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Describe the problem.
      placeholder: What did you do, and what did you see?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: translation-service
    attributes:
      label: Translation service (if applicable)
      description: The service/provider you selected in PairTranslate.
      placeholder: Google / DeepL / Bing / ChatGPT / Claude / Gemini / ...

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Include version.
      placeholder: Chrome 120.0.6099.109 / Firefox 121 / Edge 120 / ...
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Please provide the PairTranslate extension version
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Please provide your operating system
      placeholder: e.g., Windows 11, macOS 14.0, Ubuntu 22.04

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Please copy and paste any error messages from the browser console
      placeholder: Paste console errors here
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste them

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I searched existing issues
          required: true
