---
name: ✨ Feature Request
description: Suggest a new feature or improvement for PairTranslate
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks! Keep it short and concrete.

  - type: textarea
    id: feature-description
    attributes:
      label: What do you want?
      description: Describe the feature or change.
      placeholder: I want PairTranslate to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Why?
      description: The problem/use case this solves.
      placeholder: When I..., it's hard because...

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Optional, helps triage.
      options:
        - New Translation Service
        - User Interface Improvement
        - Settings/Configuration
        - Performance Optimization
        - Website Compatibility
        - Translation Quality
        - Keyboard Shortcuts
        - Accessibility
        - Mobile Support
        - Other

  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: Screenshots, links, examples, mockups.
      placeholder: Drag & drop images, or paste links

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I searched existing issues
          required: true
