---
name: 🔒 Security Issue
description: Report a security vulnerability
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        # 🔒 Security Vulnerability Report

        **IMPORTANT**: This is for reporting security vulnerabilities only.
        If this is not a security issue, please use one of the other issue templates.

        Security reports will be handled privately and may not be publicly visible.
        For immediate security concerns, please consider contacting us directly through our security contact channels.

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Please provide a clear description of the security vulnerability
      placeholder: Describe the security issue in detail. What is vulnerable and what is the impact?
    validations:
      required: true

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - XSS (Cross-Site Scripting)
        - Data Exposure/Leakage
        - API Key Exposure
        - Injection (SQL, Code, etc.)
        - Authentication/Authorization Issue
        - Sensitive Data in Storage
        - Man-in-the-Middle
        - Content Security Policy Violation
        - Cross-Site Request Forgery (CSRF)
        - Information Disclosure
        - Other
    validations:
      required: true

  - type: textarea
    id: impact-assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: Explain what an attacker could do with this vulnerability (e.g., access user data, steal API keys, execute malicious code, etc.)
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Detailed steps to reproduce the vulnerability
      placeholder: Provide step-by-step instructions on how to reproduce this security issue
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the extension are affected?
      placeholder: Content scripts, background scripts, storage, API communications, specific translation services, etc.

  - type: textarea
    id: environment-conditions
    attributes:
      label: Environment Conditions
      description: Are there specific conditions required for exploitation?
      placeholder: Specific browser versions, operating systems, translation services, user settings, etc.

  - type: dropdown
    id: user-data-affected
    attributes:
      label: User Data Affected
      description: What type of user data could be compromised?
      options:
        - Translation history/cache
        - API keys/tokens
        - Personal information
        - Browsing activity
        - Extension settings
        - No user data affected
        - Other
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Please provide a proof of concept if available
      placeholder: Code snippets, screenshots, or detailed explanation demonstrating the vulnerability
      render: shell

  - type: textarea
    id: mitigation-suggestions
    attributes:
      label: Mitigation Suggestions
      description: Do you have suggestions for how to fix this vulnerability?
      placeholder: Suggest potential fixes or security measures

  - type: dropdown
    id: disclosure-policy
    attributes:
      label: Disclosure Preference
      description: How would you like this issue to be handled?
      options:
        - Private (recommended) - Keep issue private until fixed
        - Coordinated disclosure - Work with us on disclosure timeline
        - Public disclosure - Can be discussed publicly
      default: 0
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other security-related information
      placeholder: Additional details about the vulnerability, related security concerns, etc.

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Security Acknowledgments
      description: Please confirm the following
      options:
        - label: This is a legitimate security vulnerability report
          required: true
        - label: I understand this will be handled according to our security policy
          required: true
        - label: I will not publicly disclose this issue until it has been resolved
          required: true
        - label: I have provided sufficient information to reproduce the vulnerability
          required: true

  - type: markdown
    attributes:
      value: |
        ## 🙏 Thank You

        We take security reports very seriously and appreciate your help in keeping PairTranslate safe for all users.

        **Note**: Security reports may be converted to private issues and handled through our responsible disclosure process.
