---
name: 🌐 Translation Service Issue
description: Report issues with specific translation services (Google, DeepL, ChatGPT, etc.)
title: "[Translation Service]: "
labels: ["translation-service"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for issues specifically related to translation services. For general bugs, use the Bug Report template.

  - type: dropdown
    id: translation-service
    attributes:
      label: Translation Service
      description: Which translation service is experiencing issues?
      options:
        - Google Translate
        - DeepL
        - Bing Translate
        - ChatGPT (OpenAI)
        - Claude (Anthropic)
        - Gemini (Google)
        - Multiple services
    validations:
      required: true

  - type: dropdown
    id: service-type
    attributes:
      label: Service Type
      description: What type of translation service is this?
      options:
        - Traditional Translation API
        - LLM-based Translation
        - Custom API Integration
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what's wrong with the translation service
      placeholder: The translation service is not working correctly because...
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you experiencing?
      options:
        - Translation Quality (inaccurate translations)
        - API Errors (rate limits, authentication failures)
        - Connection Issues (timeout, network errors)
        - Configuration Problems (API keys, settings)
        - Service Outage (service appears to be down)
        - Cost/Quota Issues
        - Other
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Please copy and paste any error messages you're seeing
      placeholder: Paste error messages here
      render: shell

  - type: textarea
    id: test-text
    attributes:
      label: Test Text
      description: Provide sample text that fails to translate
      placeholder: Enter the text you're trying to translate

  - type: textarea
    id: expected-translation
    attributes:
      label: Expected Translation
      description: What should the text translate to?
      placeholder: The expected translation result

  - type: textarea
    id: actual-result
    attributes:
      label: Actual Result
      description: What did you actually get?
      placeholder: The actual translation result or error

  - type: textarea
    id: source-target-languages
    attributes:
      label: Language Pair
      description: What languages are you translating between?
      placeholder: "Source: English → Target: Spanish"

  - type: input
    id: api-key-status
    attributes:
      label: API Key Status
      description: If using an API-based service, is your API key configured and valid?
      placeholder: Yes/No/Not sure

  - type: dropdown
    id: frequency
    attributes:
      label: Issue Frequency
      description: How often does this issue occur?
      options:
        - Every time
        - Frequently (>50% of attempts)
        - Sometimes (10-50% of attempts)
        - Rarely (<10% of attempts)
        - Just once
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the issue
      placeholder: |
        1. Select text: '...'
        2. Choose translation service: '...'
        3. Click translate
        4. Error occurs

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help diagnose the issue
      placeholder: Additional context, recent changes, etc.

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Steps
      description: What troubleshooting steps have you already tried?
      options:
        - label: I've checked my API key configuration
        - label: I've tried different text samples
        - label: I've tested with different language pairs
        - label: I've tried disabling other extensions
        - label: I've checked the service status page
        - label: I've tried clearing browser cache/cookies

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have checked if the translation service is experiencing an outage
          required: true
        - label: I have provided all requested information about the service issue
          required: true
