---
name: 🌍 Website Compatibility Issue
description: Report issues with PairTranslate not working on specific websites
title: "[Website Compatibility]: "
labels: ["website-compatibility"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for issues where PairTranslate doesn't work properly on specific websites. This includes problems with content detection, translation positioning, or conflicts with website scripts.

  - type: input
    id: website-url
    attributes:
      label: Website URL
      description: The URL where the issue occurs
      placeholder: https://example.com/specific-page
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what's happening (or not happening) on this website
      placeholder: PairTranslate is not working properly on this website because...
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of compatibility issue are you experiencing?
      options:
        - Translation Not Triggering (hover/select not working)
        - Translation Positioning (appears in wrong location)
        - Text Detection (not finding translatable text)
        - Visual Conflicts (overlapping, styling issues)
        - Website Scripts Blocking Extension
        - Performance Issues (slow on this site)
        - Translation Not Showing
        - Multiple/Repeated Translations
        - Other
    validations:
      required: true

  - type: textarea
    id: specific-elements
    attributes:
      label: Specific Elements
      description: Which elements on the page are causing issues? (be as specific as possible)
      placeholder: The issue occurs when I hover over navigation menu items, or when trying to translate paragraphs in the main content area...

  - type: dropdown
    id: translation-method
    attributes:
      label: Translation Method
      description: Which translation method are you using?
      options:
        - Select to Translate
        - In-text Translate
        - Keyboard Shortcut
        - Multiple methods
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Detailed steps to reproduce the issue on this website
      placeholder: |
        1. Navigate to https://example.com
        2. Scroll to the main content area
        3. Hover over the first paragraph
        4. Notice that translation doesn't appear or appears incorrectly
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen on this website?
      placeholder: The translation should appear smoothly when I hover over text...

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: The translation either doesn't appear, appears in the wrong place, or causes visual issues...

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Edge
        - Safari
        - Other
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any JavaScript errors in the browser console when on this website?
      placeholder: Paste console errors here
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots showing the issue on the website
      placeholder: Drag and drop images here or paste them

  - type: textarea
    id: website-technologies
    attributes:
      label: Website Technologies (if known)
      description: Do you know what technologies this website uses? (React, Vue, Angular, etc.)
      placeholder: This website appears to use React and Tailwind CSS...

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Steps
      description: What have you already tried?
      options:
        - label: I've tried disabling other browser extensions
        - label: I've tested on a different browser
        - label: I've cleared browser cache and cookies
        - label: I've tried different translation methods
        - label: I've tested on different pages of the same website
        - label: I've checked if the site works in incognito/private mode

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information about the website or issue
      placeholder: This website uses a lot of JavaScript, has complex layouts, requires login, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have tested this on multiple pages of the website (if applicable)
          required: true
        - label: I have provided the exact URL where the issue occurs
          required: true
        - label: The issue is specific to this website (other sites work fine)
          required: true
